GET http://localhost:8100/
Accept: */*
Cache-Control: no-cache

### Game of thrones
GET http://localhost:8100/got
Accept: */*
Cache-Control: no-cache

### animal
GET http://localhost:8100/animal
Accept: */*
Cache-Control: no-cache

### Books - Unauthenticated access result
GET http://localhost:8100/books
Accept: */*
Cache-Control: no-cache

### Books - Authenticated access result
GET http://localhost:8100/books
Authorization: Basic admin admin#
Accept: */*
Cache-Control: no-cache

### One single book, in this case for 1984 by George Orwell.
GET http://localhost:8100/books/9780451524935
Accept: */*
Cache-Control: no-cache

### Create book
POST http://localhost:8100/books
Accept: */*
Cache-Control: no-cache

title="The Lord of the Rings" \   isbn="9780618640157" \   authors:='["J.R.R. Tolkien"]'



###
