server:
  port: 8100

spring:
  jpa:
    hibernate:
      ddl-auto: none
  jackson:
    default-property-inclusion: NON_EMPTY
  datasource:
    url: jdbc:mysql://localhost:6604/explorecali
    username: cali_user
    password: cali_pass
    initialization-mode: always

logging:
  path: logs
  file: ${logging.path}/myapp.log

#application-specific string used to encrypt tokens
security:
  jwt:
    token:
      secret-key: secret-key-for-encryption
      # token valid for 10 minutes
      expiration: 600000
