server:
  port: 8100

spring:
  datasource:
    url: ${db.url} #jdbc:mysql://localhost:3306/mysql
    username: ${db.user} #root
    password: ${db.password}
  jpa:
    hibernate:
      ddl-auto: update
