spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customers
    username: customers
    password: customers
  flyway:
    baseline-on-migrate: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          fetch_size: 250
          batch_size: 50
  data:
    jpa:
      repositories:
        enabled: true # we can deactivate it if necessary
server:
  port: 8100
