spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tdd-workshop
    username: tdd
    password: workshop
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true

logging:
  level:
    org:
      springframework: off
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql.BasicBinder: TRACE
